# kubernetes-config/personal-portfolio.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-portfolio
  labels:
    app: personal-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-portfolio
  template:
    metadata:
      labels:
        app: personal-portfolio
    spec:
      containers:
      - name: personal-portfolio
        image: gcr.io/celestial-ridge-273419/personal-portfolio:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: personal-portfolio
spec:
  selector:
    app: personal-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: personal-portfolio
spec:
  tls:
    - hosts:
        - "test.nitin-kumar.com"
        - "*.test.nitin-kumar.com"
      secretName: nitin-kumar-com-tls
  rules:
    - host: www.test.nitin-kumar.com
      http:
        paths:
          - path: /
            backend:
              serviceName: personal-portfolio
              servicePort: 80
    - host: test.nitin-kumar.com
      http:
        paths:
          - path: /
            backend:
              serviceName: personal-portfolio
              servicePort: 80