version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: sudo apt-get update

      - run: sudo apt-get install git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies yep
      - run: git submodule sync && git submodule update --init

      - run: ls