version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: apt-get update

      - run: apt-get install git -y

      - run: curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \ | grep  browser_download_url \ | grep Linux-64bit.deb \ | grep -v extended \ | cut -d '"' -f 4 \ | wget -i -

      - run: dpkg -i hugo*_Linux-64bit.deb
      
      # checkout the repository
      - checkout

      # hugo build
      - run: hugo