version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: apt-get update

      - run: apt-get install git -y

      - run: apt-get install hugo -y

      # checkout the repository
      - checkout

      # hugo build
      - run: hugo